import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';


export default function Home() {
  return (
    <div >
      <Head>
        <title>Alex Gathungu portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <main >
     <section className="min-h-screen">
      <nav>
       <h1>My Portfolio</h1>
       <il>
        <li> BsFillMoonStarsFill</li>
        <li><a href="linkdin">cv</a></li>
       </il>
      </nav>





      </section>
       
      </main>

     
    </div>
  )
}
